spring:
  application:
    name: 'drinkshop-telegrambot'
  main:
    banner-mode: off
    web-application-type: servlet
  kafka:
    bootstrap-servers: 'localhost:9091'
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: 'drinkshop-mainservice'
    streams:
      application-id: 'drinkshop-mainservice'
      replication-factor: 1
      properties:
        commit.interval.ms: 2000
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        processing.guarantee: exactly_once_v2

app:
  client:
    telegramservice: http://localhost:8080/api/telegram
  bot:
    name: Kam333555Bot
    token: 7166981536:AAG9J4o1hYRzoTLuL9bF63kQd8vZ9tKqFlo

server:
  port: 8085