filebeat.inputs:
  - type: filestream
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'

output.logstash:
  hosts: ["logstash:5044"]

processors:
  - add_docker_metadata:
      host: "unix:///host_docker/docker.sock"