spring:
  application:
    name: 'customerservice'
  main:
    banner-mode: 'off'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5441/postgres'
    username: postgres
    password: postgres
  jackson:
    default-property-inclusion: non_empty
  liquibase:
    enabled: true
    change-log: changelog.sql
    driver-class-name: org.postgresql.Driver
    user: postgres
    password: postgres
    url: 'jdbc:postgresql://localhost:5441/postgres'
  kafka:
    bootstrap-servers: 'localhost:9091'
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: 'customerservice'
    consumer:
      properties:
        spring.json.trusted.packages: "*"
      group-id: 'customerservice'
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    streams:
      application-id: 'customerservice-streams'
      replication-factor: 1
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$UUIDSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        spring.json.trusted.packages: "*"

SECRET_KEY: 12412561235231562356234532542354623546235462

server:
  port: 8091