INSERT INTO product(name, price)
VALUES ('Горячий Шоколад 200мл', 250),
       ('Капучино 350мл', 350),
       ('Капучино 450мл', 250),
       ('Латте Макиато 350мл', 350),
       ('Латте Макиато 450мл', 500),
       ('Английский Завтрак 350мл', 500),
       ('Английский Завтрак 450мл', 500),
       ('Чарльз Эрл Грей 350мл', 500),
       ('Чарльз Эрл Грей 450мл', 500),
       ('Какао Классический 350мл', 500),
       ('Какао Классический 450мл', 500),
       ('Какао Солёная Карамель 350мл', 500),
       ('Какао Солёная Карамель 450мл', 500),
       ('Айс Крим Латте Классический 350мл', 500),
       ('Айс Крим Латте Классический 450мл', 500),
       ('Айс Крим Латте Солёная Карамель 350мл', 500),
       ('Айс Крим Латте Солёная Карамель 450мл', 500),
       ('Милкшейк Классический 350мл', 500),
       ('Милкшейк Классический 450мл', 500);

INSERT INTO product_inventory_type(name)
VALUES ('Молоко'),
       ('Чай'),
       ('Шоколад');

INSERT INTO product_inventory(product_id, product_inventory_type_id, quantity)
VALUES ((select id from product t where t.name = 'Горячий Шоколад 200мл'),
        (select id from product_inventory_type t where t.name = 'Молоко'),
        100),
       ((select id from product t where t.name = 'Горячий Шоколад 200мл'),
        (select id from product_inventory_type t where t.name = 'Чай'),
        100),
       ((select id from product t where t.name = 'Капучино 350мл'),
        (select id from product_inventory_type t where t.name = 'Молоко'),
        100),
       ((select id from product t where t.name = 'Капучино 450мл'),
        (select id from product_inventory_type t where t.name = 'Молоко'),
        100),
       ((select id from product t where t.name = 'Латте Макиато 350мл'),
        (select id from product_inventory_type t where t.name = 'Молоко'),
        100),
       ((select id from product t where t.name = 'Латте Макиато 450мл'),
        (select id from product_inventory_type t where t.name = 'Молоко'),
        100),
       ((select id from product t where t.name = 'Английский Завтрак 350мл'),
        (select id from product_inventory_type t where t.name = 'Молоко'),
        100),
       ((select id from product t where t.name = 'Английский Завтрак 450мл'),
        (select id from product_inventory_type t where t.name = 'Молоко'),
        100),
       ((select id from product t where t.name = 'Чарльз Эрл Грей 350мл'),
        (select id from product_inventory_type t where t.name = 'Молоко'),
        100),
       ((select id from product t where t.name = 'Чарльз Эрл Грей 450мл'),
        (select id from product_inventory_type t where t.name = 'Молоко'),
        100),
       ((select id from product t where t.name = 'Какао Классический 350мл'),
        (select id from product_inventory_type t where t.name = 'Молоко'),
        100),
       ((select id from product t where t.name = 'Какао Классический 450мл'),
        (select id from product_inventory_type t where t.name = 'Молоко'),
        100),
       ((select id from product t where t.name = 'Какао Солёная Карамель 350мл'),
        (select id from product_inventory_type t where t.name = 'Молоко'),
        100),
       ((select id from product t where t.name = 'Какао Солёная Карамель 450мл'),
        (select id from product_inventory_type t where t.name = 'Молоко'),
        100),
       ((select id from product t where t.name = 'Айс Крим Латте Классический 350мл'),
        (select id from product_inventory_type t where t.name = 'Молоко'),
        100),
       ((select id from product t where t.name = 'Айс Крим Латте Классический 450мл'),
        (select id from product_inventory_type t where t.name = 'Молоко'),
        100),
       ((select id from product t where t.name = 'Айс Крим Латте Солёная Карамель 350мл'),
        (select id from product_inventory_type t where t.name = 'Молоко'),
        100),
       ((select id from product t where t.name = 'Айс Крим Латте Солёная Карамель 450мл'),
        (select id from product_inventory_type t where t.name = 'Молоко'),
        100),
       ((select id from product t where t.name = 'Милкшейк Классический 350мл'),
        (select id from product_inventory_type t where t.name = 'Молоко'),
        100),
       ((select id from product t where t.name = 'Милкшейк Классический 450мл'),
        (select id from product_inventory_type t where t.name = 'Молоко'),
        100);

INSERT INTO shop(name, location, status)
VALUES ('Грин хауc №1', 'Улица №1', 'OK');

INSERT INTO shop_inventory(shop_id, product_inventory_type_id, quantity)
VALUES ((select id from shop t where t.name = 'Грин хауc №1'), (select id from product_inventory_type t where t.name = 'Молоко'), 1000),
       ((select id from shop t where t.name = 'Грин хауc №1'), (select id from product_inventory_type t where t.name = 'Чай'), 1000),
       ((select id from shop t where t.name = 'Грин хауc №1'), (select id from product_inventory_type t where t.name = 'Шоколад'), 1000);

INSERT INTO customer(telegram_id, name, points, phone_number, qr_code, qr_code_expires_at)
VALUES ('telegram_id', 'name', 100, 'phone_number', '123456', '9999-01-01')