apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerservice-deployment
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: customerservice
  template:
    metadata:
      labels:
        app: customerservice
    spec:
      containers:
        - name: customerservice-container
          image: slow3586/drinkshop:customerservice-0.0.1
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: management.zipkin.tracing.endpoint
              value: http://zipkin-service:9411/api/v2/spans
            - name: spring.datasource.url
              value: jdbc:postgresql://customerservice-postgres-service:5432/postgres
            - name: KAFKA_BROKERS
              value: kafka-service:9092
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: customerservice-service
  labels:
    app: customerservice
spec:
  type: NodePort
  selector:
    app: customerservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: web
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: customerservice-monitor
spec:
  selector:
    matchLabels:
      app: customerservice
  endpoints:
    - interval: 15s
      port: web
      path: /actuator/prometheus