spring:
  application:
    name: 'drinkshop-cashiermenu'
  main:
    web-application-type: servlet
    banner-mode: 'off'
  devtools:
    livereload:
      enabled: true
  web:
    resources:
      static-locations:
        - 'file:src/main/resources/static/'
        - 'classpath:/static/'
  output:
    ansi:
      enabled: ALWAYS
server:
  compression:
    enabled: true
  port: 8082