spring:
  application:
    name: 'drinkshop-mainservice'
  main:
    banner-mode: 'off'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5434/postgres'
    username: postgres
    password: postgres
  jackson:
    default-property-inclusion: non_absent
server:
  port: 8081